move css over to oranda
axodotdev/oranda pull request #200
Opened 2023-03-07 00:55 UTC by SaraVieira

2023-03-07 20:04 UTC, ashleygwilliams requested changes
in general i think this is looking good- i do think we should not nest the css in the rust source code.. we should pull it up to the top as an additional project almost. it can't be treated like a local asset because it will not be bundled in the binary- so we will need to write an action to publish the css to github releases- where we can fetch it

2023-03-07 20:04 UTC, ashleygwilliams commented on docs/configuration/theme.md
> +Themes can be further customized by adding extra CSS.
this feels repetitive to the next line

2023-03-08 11:05 UTC, SaraVieira commented
About your comment, i assumed that was the idea, i would make it work this way, copy everything and then you would come to the PR and do your releasing magic so we could merge

2023-03-08 15:21 UTC, ashleygwilliams commented on src/site/layout/footer.rs
> +        <footer class="footer">
should this be a class or should it just target the footer element?

2023-03-08 15:21 UTC, ashleygwilliams commented on src/site/layout/footer.rs
> +        <footer class="footer">
@SaraVieira ^

2023-03-09 16:10 UTC, ashleygwilliams commented on src/site/layout/footer.rs
> +        <footer class="footer">
filed as #205

2023-03-10 01:58 UTC, ashleygwilliams approved these changes
still has issues (#212, #204) but let's merge this

2023-03-10 13:14 UTC, merged