Analytics
axodotdev/oranda pull request #38
Opened 2022-12-21 21:43 UTC by SaraVieira

Adds ability to configure analytics with the following options:

- Google
	- tracking_id
- Fathom
	- site
- Plausible
	- domain
	- script_url -> Optional, defaults to "https://plausible.io/js/script.js" 
- Unami
	- website
	- script_url 

closes https://github.com/axodotdev/oranda/issues/36

2023-01-02 23:07 UTC, ashleygwilliams requested changes
small changes, feel free to push back or ask follow ups, mostly just prefs, nothing big

2023-01-02 23:07 UTC, ashleygwilliams commented on oranda.json
> +      "domain": "oranda.axo.dev"
i strongly suspect this url is gonna be https://tools.axo.dev/oranda, but this is just used for testing ya?

2023-01-02 23:07 UTC, ashleygwilliams commented on src/config/analytics.rs
> +pub fn get_google_script(config: &Config) -> Option<Box<script<String>>> {
i might do this as an `impl GoogleTracking` since it's just related to that one and is using just that config

2023-01-02 23:07 UTC, ashleygwilliams commented on src/config/oranda.rs
> +use super::analytics::Analytics;
can we rewrite this to use something other than super? we use crate a lot and i figure it's good to be consistent

2023-01-02 23:39 UTC, SaraVieira commented on oranda.json
> +      "domain": "oranda.axo.dev"
yeah but might aswell do it right now

2023-01-02 23:41 UTC, SaraVieira commented on src/config/oranda.rs
> +use super::analytics::Analytics;
sure! Done, didn't catch it

2023-01-02 23:42 UTC, SaraVieira commented on src/config/analytics.rs
> +pub fn get_google_script(config: &Config) -> Option<Box<script<String>>> {
Can you please give some follow up? I don't think I really understand the `impl` thing, some links would also be good so i could take a look tomorrow

2023-01-03 17:12 UTC, SaraVieira commented on src/config/analytics.rs
> +pub fn get_google_script(config: &Config) -> Option<Box<script<String>>> {
nvm I figured it out

let me know if it's okay

2023-01-17 14:56 UTC, ashleygwilliams reviewed
if i am reading this correctly- if there isn't a google script- this would still call "get google script" and add it to the page? if we want to merge this we need to open an issue to fix that because not every page will use a google script.

it would also be helpful for us to get some tests for this! but we can open that as a separate issue

2023-01-17 17:06 UTC, ashleygwilliams approved these changes
good for now, based on pairing

2023-01-17 17:38 UTC, merged