Remove unwrap
axodotdev/oranda pull request #50
Opened 2022-12-23 18:50 UTC by SaraVieira

Removes an uneeded unwrap, fixed by matching and just doing nothing in the case there are no additional files

related https://github.com/axodotdev/oranda/issues/48

2023-01-05 19:17 UTC, ashleygwilliams requested changes

2023-01-05 19:17 UTC, ashleygwilliams commented on src/site/mod.rs
> +        match &config.additional_pages {
i think an if let is probably a better fit here if we dont intend to handle the None case

2023-01-06 18:46 UTC, SaraVieira commented on src/site/mod.rs
> +            files.extend(pages);
Changed it here but I get a weird error: 

<img width="647" alt="CleanShot 2023-01-06 at 18 45 21@2x" src="https://user-images.githubusercontent.com/1051509/211078379-53cfd9b0-9805-4bf9-8a4b-78fd416151b5.png">


cc @ashleygwilliams

2023-01-16 18:41 UTC, ashleygwilliams commented on src/site/mod.rs
> +            files.extend(pages);
oh huh mmm - mind if i pull this down and poke at it?

2023-01-16 19:15 UTC, SaraVieira commented on src/site/mod.rs
> +            files.extend(pages);
Of course not :)

2023-01-16 22:40 UTC, ashleygwilliams commented on src/site/mod.rs
> +        let readme_path = config.readme_path.clone();
smol crime, it's fine

2023-01-16 22:40 UTC, ashleygwilliams commented on src/site/mod.rs
> +        let files = if let Some(mut pages) = config.additional_pages.clone() {
same here

2023-01-17 14:08 UTC, ashleygwilliams commented
i think we should close this as the original code is slightly better than this change and i think it will become irrelevant with the larger changes we'll be making soon

2023-01-17 14:08 UTC, closed without merging