Add install-widget to release pages
axodotdev/oranda pull request #507
Opened 2023-07-03 18:22 UTC by Gankra

This uses the fact that the install-widget was always release-specific, so we can generate different copies for every install page

2023-07-03 18:23 UTC, Gankra commented
<img width="1114" alt="Screen Shot 2023-07-03 at 2 22 51 PM" src="https://github.com/axodotdev/oranda/assets/1136864/c84451da-250d-4047-8a8b-547e4b16a80b">

2023-07-03 18:25 UTC, Gankra commented
Also note that, as discussed in the Long Long Ago, "view source" here is not the Rich View Source we give to the latest release. It hotlinks the github download for the script, to avoid downloading+hosting a million scripts.

2023-07-03 18:26 UTC, Gankra commented
"View all installation options" will also link the downloads page, which is just the latest download. Kinda bleh.

2023-07-03 18:29 UTC, Gankra commented
The package-manager strings are also "wrong" in that they aren't templated to specify the version to install.

2023-07-04 09:52 UTC, shadows-withal approved these changes
I think this works as a "suboptimal" feature for now (I think it satisfies Most use-cases)

2023-07-04 15:50 UTC, ashleygwilliams requested changes
i think there's design work we need to do before this is shipped- can talk more in the product meeting on thursday

2023-08-25 12:15 UTC, shadows-withal commented
Closing due to several reasons:

- We most likely want to avoid making a changelog page _too_ much like the index page
- There would have to be more design decisions around templating (where do we insert the version to install? is it up to the user? what syntax does this use? etc)
- This PR is incompatible with the ongoing work around separating the install widget from oranda itself

2023-08-25 12:15 UTC, closed without merging