wip: template refactor
axodotdev/oranda pull request #526
Opened 2023-07-11 16:04 UTC by shadows-withal

Refactors the code to use minijinja instead of axohtml. Huge WIP.

2023-07-13 18:30 UTC, Gankra approved these changes
A few nits about unwraps, but looks good. Only reviewed the rust, didn't review the templates (seems impractical to try to do).

2023-07-13 18:30 UTC, Gankra commented on src/site/artifacts/mod.rs
> +type Platforms = HashMap<TargetTriple, Vec<InstallerIdx>>;
If this is getting fed into templates, do we want it to be BtreeMap/IndexMap? (It was a HashMap only because I knew it wouldn't show up in output)

2023-07-13 18:30 UTC, Gankra commented on src/site/artifacts/mod.rs
> +type Platforms = HashMap<TargetTriple, Vec<InstallerIdx>>;
Also iirc I had some doc-comments describing how these are interpreted, might be worth transplanting them here too?

2023-07-13 18:30 UTC, Gankra commented on src/site/artifacts/mod.rs
> +        };
wait did rustfmt actually generate this? 0.o

(i think rustfmt support for let-else might only be on the latest toolchain)

2023-07-13 18:30 UTC, Gankra commented on src/site/funding/mod.rs
>          let preferred = unwrapped_config.preferred_funding.as_ref().unwrap();
should be updated to an if-let

2023-07-13 18:30 UTC, Gankra commented on src/site/funding/mod.rs
> +        funding_base.remove(preferred);
Is this unwrap correct? What if the user typo's the key?

Regardless you can replace this with `let content = funding_base.remove(preferred);` (give or take the unwrap)

2023-07-13 18:30 UTC, Gankra commented on src/site/layout/header.rs
> +) -> Result<String> {
Does some later code properly apply this now..? (maybe rename the function to get_logo_url if so..?)

2023-07-13 18:30 UTC, Gankra commented on src/site/mod.rs
> +                config.styles.favicon.as_ref().unwrap(),
should be if-let

2023-07-13 18:30 UTC, Gankra commented on src/site/oranda_theme.rs
> +    #[serde(alias = "axo_dark", rename(serialize = "dark axo"))]
wait, the light theme is "the" axo theme? that's backwards, no?

2023-07-13 18:30 UTC, Gankra commented on src/site/templates.rs
> +const TEMPLATE_DIR: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/templates");
woah, wild that include_dir provides this sugar

2023-07-13 18:30 UTC, Gankra commented on src/site/templates.rs
> +        }
these shouldn't ever fail in prod but it would be nice to make these expects to save debugging time when developing?

2023-07-13 18:30 UTC, Gankra commented on src/site/templates.rs
> +                let file_name = file_path.with_extension("");
TIL this is an officially documented way to pop one part of the extension

2023-07-13 18:30 UTC, Gankra commented on src/site/templates.rs
> +            Err(_) => format!("<code class='inline-code'>{code}</code>"),
Is this like the last place in our code where we randomly have some inline-html in rust?

2023-07-13 22:38 UTC, Gankra commented
Pushed up some resolutions of most of my comments. I ended up doing a quick pass over all the `unwraps` in non-test code and either replaced them or upgraded them to an `expect` with some description of why they shouldn't happen in prod, ostensibly.

I added a couple TODOs for genuine questions I don't want to unilaterally make a call on.

2023-07-13 22:40 UTC, Gankra requested changes

2023-07-13 22:40 UTC, Gankra commented on src/site/artifacts/mod.rs
> +type DownloadableFiles = Vec<(FileIdx, (File, Vec<Option<String>>))>;
TODO

2023-07-13 22:40 UTC, Gankra commented on src/site/artifacts/mod.rs
> +type Platforms = HashMap<TargetTriple, Vec<InstallerIdx>>;
SEMI-TODO

2023-07-13 22:40 UTC, Gankra commented on src/site/funding/mod.rs
> +            None
TODO

2023-07-13 22:40 UTC, Gankra commented on src/site/templates.rs
> +    }
TODO

2023-07-13 22:40 UTC, Gankra commented on tests/build/mod.rs
> +
Should be a FIXME instead?

2023-07-13 22:41 UTC, Gankra commented on src/site/oranda_theme.rs
> +    #[serde(alias = "axo_dark", rename(serialize = "dark axo"))]
still TODO

2023-07-13 22:44 UTC, Gankra commented on tests/build/mod.rs
> +
https://github.com/axodotdev/oranda/issues/528

2023-07-14 12:55 UTC, Gankra approved these changes

2023-07-14 16:13 UTC, ashleygwilliams approved these changes

2023-07-14 16:13 UTC, merged