Logo
axodotdev/oranda pull request #53
Opened 2023-01-03 19:32 UTC by SaraVieira

Adds ability to have a logo

2023-01-04 16:01 UTC, SaraVieira commented
@ashleygwilliams I know axo asset is not done, but I would appreciate your review here, I don't like my code but can't think if a better way

2023-01-17 22:09 UTC, ashleygwilliams requested changes

2023-01-17 22:09 UTC, ashleygwilliams commented on src/site/html.rs
> +    <link rel="stylesheet" href="https://market-assets.fra1.cdn.digitaloceanspaces.com//themes/axo-oranda.css" />    <link rel="stylesheet" href="styles.css"></link>
⚠️

2023-01-17 22:27 UTC, ashleygwilliams approved these changes

2023-01-17 22:36 UTC, merged